apiVersion: app/v1
kind: Deployment
metadata: 
  name: cloudage
  spec: 
    selector: 
      matchLabels:
        app: cloudage
    replicas: 2
    strategy:
      type: RollingUpdate
      rollingUpdate: 
        maxSurge: 1
        maxUnavailable: 1
    template: 
      metadata:
        labels: 
          app: cloudage
      spec:
        containers: 
        - name: cloudage
          image: tabrezid54/cloudjob
          imagePullPolicy: Always
          ports: 
          - containerPort: 80
